# Docker compose file version
version: "3.6"

services:
  # Web App #
  web:
    image: node:14
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: < 
      bash -c "nmp install && npm start"
  
  # DB
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db_name"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass123"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql